### ISSUE TITLE
Accessing to log file

### ISSUE THREAD

**Issue by pouyan-asg** [Kinovarobotics/Kortex3#4]
I have a quick question about Link 6:

In general, is it possible that users have access to log files, or should only the Kinova company check them?
When I download Logs or Configuration in Maintenance mode (when log in) , the downloaded file is a ZIP with a password.

Thank you
Regards,

**Comment by martinleroux** [comment]
The log files are password protected and are only meant to be read by Kinova staff.

If you want to lookup information in your log files, for example to follow a chain of event which lead to a fault, please contact support@kinova.ca
