### ISSUE TITLE
Stopping the Running Code

### ISSUE THREAD

**Issue by pouyan-asg** [Kinovarobotics/Kortex3#5]
Hello Kinova Team,

In order to connect to the Link6 robot and provide commands, I'm using Visual Studio Code. When I was using Gen3, I could previously stop code execution from my IDE, and the robot simply could stop at that time. However, Link6 will continue executing waypoints after I stop the code. I also tried running code through the command prompt, and the robot could not stop after killing code (ctrl+C or ctrl+pause).
I looked into the specifics to see how I could modify that, but I was unsuccessful in resolving the problem. 

**I'm curious whether there is a way to kill the code to stop the robot at each deliberate point? Or do I always have to wait for the robot to finish waypoint execution?** 

Thank you very much for your time and consideration.

Regards,
Pouyan

**Comment by OusmaneMuskoka** [comment]
Hey Pouyan, I found a possible solution on my end. Calling base.Stop() will halt current movements. there is also a quick stop and stop actions. I am wrapping my movements in a try block, and calling stop in the finally call, since it will be called on program exit, including when exiting from debugging. 

```
        try:
            complete_movements(base, io_client, router)
        except KeyboardInterrupt:
            print("Interrupted by user, shutting down")
        finally:
            print("Stopping the arm")
            base.Stop()
```

**Comment by martinleroux** [comment]
I confirm the proper way to interrupt the robot is either to use
base.Stop()
or
programrunner.Stop() depending on whether you are moving the robot via programs or base actions. (note that programrunner.Pause() also exist should you want to resume after pausing).
