### ISSUE TITLE
Screenshot on the Kortex3/json_program_samples/004-Industrial IOs not working

### ISSUE THREAD

**Issue by chilijon** [Kinovarobotics/Kortex3#6]
I was looking to see the way to connect a separate machinery to the link 6 controller but the screenshot didn't  work.
Please.

![image](https://github.com/Kinovarobotics/Kortex3/assets/145138479/c76f87c6-cfc9-4988-a7e2-dcfb00d3a438)
[](url)
![Capture d’écran 2023-09-15 105315](https://github.com/Kinovarobotics/Kortex3/assets/145138479/4122bbfb-e09e-40b7-b43f-2add3e9ed919)

**Comment by kyilmazKinova** [comment]
Hi,
Sorry about that, we'll fix the issue shortly. In the meantime, the first screenshot can be found on page 29 of the Link6 User Guide (Figure 25) and the second on page 32 (Figure 29). The User Guide contains also a lot more information on the subject.

Best regards,

**Comment by fgermainFAE** [comment]
Hi,

Sorry for the delay. We lost track of this issue after Kevin left, but it's now fixed.
